name: CI_pull_request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slbeta3
        with:
          args:
            build -c --skip-tests
        env:
          WORKING_DIR: ./excel
